from django.http import HttpResponse, JsonResponse
from django.template import loader


# Create your views here.
def members(request):
    context = {
        "data": [
            {"number": "1", "name": "rafsan"},
            {"number": "2", "name": "happp"},
            {"number": "3", "name": "rozak"},
            {"number": "4", "name": "bidun"},
            {"number": "5", "name": "adunn"},
            {"number": "6", "name": "terno"},
            {"number": "7", "name": "manusso"},
            {"number": "8", "name": "asetto"},
            {"number": "9", "name": "corss"},
            {"number": "10", "name": "testing"},
        ],
        "data1": [
            {"number": "11", "name": "muhim"},
            {"number": "12", "name": "anies"},
            {"number": "13", "name": "baswedan"},
            {"number": "14", "name": "prabwowo"},
            {"number": "15", "name": "amienn"},
            {"number": "16", "name": "raisee"},
            {"number": "17", "name": "mahmudi"},
            {"number": "18", "name": "MD"},
            {"number": "19", "name": "Termint"},
            {"number": "20", "name": "Apatuh"},
        ],
        "data2": [
            {"number": "21", "name": "muhim"},
            {"number": "22", "name": "anies"},
            {"number": "23", "name": "baswedan"},
            {"number": "24", "name": "prabwowo"},
            {"number": "25", "name": "amienn"},
            {"number": "26", "name": "raisee"},
            {"number": "27", "name": "mahmudi"},
            {"number": "28", "name": "MD"},
            {"number": "29", "name": "Termint"},
            {"number": "30", "name": "Apatuh"},
        ],
        "data3": [
            {"number": "31", "name": "muhim"},
            {"number": "32", "name": "anies"},
            {"number": "33", "name": "baswedan"},
            {"number": "34", "name": "prabwowo"},
            {"number": "35", "name": "amienn"},
            {"number": "36", "name": "raisee"},
            {"number": "37", "name": "mahmudi"},
            {"number": "38", "name": "MD"},
            {"number": "39", "name": "Termint"},
            {"number": "40", "name": "Apatuh"},
        ],
        "data4": [
            {"number": "41", "name": "muhim"},
            {"number": "42", "name": "anies"},
            {"number": "43", "name": "baswedan"},
            {"number": "44", "name": "prabwowo"},
            {"number": "45", "name": "amienn"},
            {"number": "46", "name": "raisee"},
            {"number": "47", "name": "mahmudi"},
            {"number": "48", "name": "MD"},
            {"number": "49", "name": "Termint"},
            {"number": "50", "name": "Apatuh"},
        ],
         "data5": [
            {"number": "51", "name": "muhim"},
            {"number": "52", "name": "anies"},
            {"number": "53", "name": "baswedan"},
            {"number": "54", "name": "prabwowo"},
            {"number": "55", "name": "amienn"},
            {"number": "56", "name": "raisee"},
            {"number": "57", "name": "mahmudi"},
            {"number": "58", "name": "MD"},
            {"number": "59", "name": "Termint"},
            {"number": "60", "name": "Apatuh"},
        ],
          "data6": [
            {"number": "11", "name": "muhim"},
            {"number": "12", "name": "anies"},
            {"number": "13", "name": "baswedan"},
            {"number": "14", "name": "prabwowo"},
            {"number": "15", "name": "amienn"},
            {"number": "16", "name": "raisee"},
            {"number": "17", "name": "mahmudi"},
            {"number": "18", "name": "MD"},
            {"number": "19", "name": "Termint"},
            {"number": "20", "name": "Apatuh"},
        ],
    }
    template = loader.get_template("index.html")
    return HttpResponse(template.render(context, request))
